### ISSUE TITLE
Stuck on starting

### ISSUE THREAD

**Issue by stXwinter** [v002/v002-Camera-Live#47] opened 2018-11-07 09:32 UTC
Hello? Is anyone going to reply to my previous Closed Thread question?

**Comment by Cyberpunk110** [comment] 2018-11-21 08:12
Hi, try switching to live View Mode on your camera.  
Little tutorial to show what i mean: 
https://support-sg.canon-asia.com/contents/SG/EN/8202785200.html

worked for me! Good luck

**Comment by dank81** [comment] 2018-12-07 04:16
This seems to happen when there are images stored on the camera's memory card. Try deleting the images, removing the card or changing to an empty/blank card.

Another one - if the camera's LCD display says "busy" when you try to activate Camera Live, try disconnecting and re-connecting the USB cable.

**Comment by Yashkin0** [comment] 2018-12-30 02:55
I am having an issue with this as well, my memory card is empty as suggested, but it just says starting. On the LCD screen there is a picture of a laptop. I am using a t6i and a macbook pro with the latest release of Mojave

**Comment by CookieDude2332** [comment] 2019-01-22 17:15
I too am having this same issue with my Canon 700D. Sometimes the screen will tell me to press the live view button to get it working but all my buttons stop working.

**Comment by rdmorton** [comment] 2019-01-22 18:02
It's working well on my Canon 70D.  Have you updated the firmware on your Canon?

**Comment by rdmorton** [comment] 2019-01-22 18:12
I'm using High Sierra, haven't tested this with Mojave.

**Comment by ksigWyatt** [comment] 2019-06-30 18:18
I'm having this issue also. See my comment on issue #45.

**Comment by bangnoise** [comment] 2019-11-19 21:06
Please try with [the latest release](https://github.com/v002/v002-Camera-Live/releases/latest). Closing as this issue is a duplicate of #45.

**Closed by bangnoise** 2019-11-19 21:06 UTC
