### ISSUE TITLE
Not working with Mac OSX 10.15.2

### ISSUE THREAD

**Issue by ppespepe** [v002/v002-Camera-Live#62] opened 2019-12-12 21:32 UTC
Updated to 10.15.2 and cameralive stopped communicating with the cammera.

**Comment by bangnoise** [comment] 2019-12-15 13:04
Unfortunately Canon have confirmed an issue with the Canon SDK and 10.15.2. They promise a fix but no date as yet.

**Comment by mariohernandez** [comment] 2019-12-18 21:36
Anyone has any workarounds while we way for a fix?  can't use my camera at all after latest macos update.

**Comment by tavon** [comment] 2019-12-19 20:50
+1 Same issues here. Where can we get updates on the status of Canon SDK support for Catalina 10.15.2? I searched pretty extensively on their developer forum, but I couldn't find it.

**Comment by ClearCloud8** [comment] 2019-12-24 19:46
Same issue... would love to be able to use this software on Mac OS Catalina.  This software saves me from needing to buy a Cam Link 4k....   I hope this can be fixed soon....  otherwise it's back to live streaming with crappy iSight camera instead of DSLR.  :-|

**Comment by michiels** [comment] 2019-12-29 20:36
For what it's worth, here's a statement on Canon's website indicating that they are aware: https://t.co/KFvp63zFNJ?am

**Comment by ThomasBallatore** [comment] 2020-01-16 23:52
I haven't tried yet, but comments in the link below suggest that the SDK is working again in 10.15.3 beta.

https://www.dpreview.com/forums/thread/4434325?page=2

Anyone willing to try that out and report if Camera Live is working again? I've been sticking with 10.14.6 because of this issue.

**Comment by sandeld** [comment] 2020-01-28 12:55
I just updated my Macbook to the macOS 10.15.3 beta, and it's still not working for me either. I have a Canon T2i with the latest firmware installed. 

I have confirmed that the EOS Utility Live View works, but whenever I launch Camera Live, it either crashes immediately, or it does open up but says there's a camera error. 

So, still not usable. :-(

**Comment by ThomasBallatore** [comment] 2020-01-30 05:21
And...it's working on 10.15.3! So happy to have this old friend back. In the meantime, I did by a Cam Link 4K dongle which is performing well—great to have both options again.

<img width="1680" alt="camera live working on 10 15 3" src="https://user-images.githubusercontent.com/12889483/73422244-aa8ab480-436b-11ea-9e8a-b479eb53ef93.png">

**Comment by sandeld** [comment] 2020-01-30 10:08
I just updated to 10.15.3 and it's still not working for me. :-(

It crashes immediately after I open it, and then when I click "reopen" it says Camera Error.

<img width="974" alt="Screen Shot 2020-01-30 at 11 04 41 AM" src="https://user-images.githubusercontent.com/33200379/73439949-c765be80-4350-11ea-808b-ea0847d2f8bd.png">
<img width="372" alt="Screen Shot 2020-01-30 at 11 05 04 AM" src="https://user-images.githubusercontent.com/33200379/73439969-cd5b9f80-4350-11ea-8934-a106569e0dde.png">

**Comment by bangnoise** [comment] 2020-01-30 11:11
There's a new Canon SDK release, supposedly with a fix for this issue. Just testing with it now.

**Comment by bangnoise** [comment] 2020-01-30 15:10
Fixed, please update to [the latest version](https://github.com/v002/v002-Camera-Live/releases/latest).

**Closed by bangnoise** 2020-01-30 15:10 UTC

**Comment by jrong1271** [comment] 2020-01-30 15:37
🥂 Just want to say Thank you for fixing this, you guys are amazing! 💯 👍

**Comment by ClearCloud8** [comment] 2020-01-31 01:04
It works for me as well!  Thank you so much!!  :)

**Comment by sandeld** [comment] 2020-01-31 11:57
Yessss!! Thank you so much!

**Comment by terencetyrone** [comment] 2020-10-08 18:27
Sony A7ii 
I continually get "camera error" every time I connect to my iMac. Please help!
