### ISSUE TITLE
Zoom updates -- Camera Live stops working

### ISSUE THREAD

**Issue by natedigitalchumps** [v002/v002-Camera-Live#142] opened 2020-05-19 13:10 UTC
**PLEASE COMPLETE ALL OF THIS SECTION**

**System:**
 - macOS version: MacOS 10.15.5
 - Canon 80D
 - Camera Live version 13

**Describe the bug**
When I update Zoom to the latest version, which is going to be mandatory on May 30th, Camera Live stops working and being recognized by Zoom. 

**To Reproduce**
1. Update Zoom 
2. Start Camera Live
3. It's no longer an option in Zoom's video selections

**Expected behavior**
It should see the camera, but doesn't.

**Additional context**
When I roll back to the previous Zoom it works again.

**Comment by bangnoise** [comment] 2020-05-19 14:22
Duplicate of #102 (this is a problem with Zoom and can only be fixed by them).

**Closed by bangnoise** 2020-05-19 14:22 UTC
